Repository serudda/twon, pull requests merged in 2023-05, with the labels that each got.

#7 [TW-03] add TextGradient component
  apps/nextjs/src/components/TextGradient/TextGradient.tsx
  apps/nextjs/src/components/index.ts
Labels: Type: Feature

#9 [TW-5] Connect side-ui lib
  apps/nextjs/next-i18next.config.js
  apps/nextjs/next.config.mjs
  apps/nextjs/package.json
  apps/nextjs/src/@types/i18next.d.ts
  apps/nextjs/src/pages/_app.tsx
  apps/nextjs/src/pages/auth/error.tsx
  apps/nextjs/src/pages/auth/signin.tsx
  apps/nextjs/src/pages/index.tsx
  apps/nextjs/src/styles/globals.css
  apps/nextjs/tailwind.config.ts
  package.json
  packages/api/package.json
  packages/api/src/@types/i18next.d.ts
  packages/api/src/controllers/account.controller.ts
  packages/api/src/controllers/user.controller.ts
  packages/config/i18n/package.json
  packages/config/i18n/src/i18n.ts
  packages/config/i18n/src/i18nNamespaces.ts
  packages/config/i18n/src/index.ts
  packages/config/i18n/src/locale/en/api.json
  packages/config/i18n/src/locale/en/common.json
  packages/config/i18n/src/locale/en/nextjs.json
  packages/config/i18n/src/locale/es/api.json
  packages/config/i18n/src/locale/es/common.json
  packages/config/i18n/src/locale/es/nextjs.json
  packages/config/tailwind/index.ts
  pnpm-lock.yaml
Labels: Type: Enhancement

#11 [TW-01] landing page
  apps/nextjs/next.config.mjs
  apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
  apps/nextjs/src/components/Cards/index.tsx
  apps/nextjs/src/components/Counter/Counter.tsx
  apps/nextjs/src/components/Icon/Icon.tsx
  apps/nextjs/src/components/TextGradient/TextGradient.tsx
  apps/nextjs/src/components/Typewriter/Typewriter.tsx
  apps/nextjs/src/components/index.ts
  apps/nextjs/src/pages/index.tsx
  apps/nextjs/src/styles/globals.css
  apps/nextjs/tailwind.config.ts
  pnpm-lock.yaml
Labels: Type: Enhancement, Type: Feature

#13 add a landing page: 0.0.0 → 0.1.0-alpha (minor)
  apps/nextjs/next-i18next.config.js
  apps/nextjs/next.config.mjs
  apps/nextjs/package.json
  apps/nextjs/public/favicon.ico
  apps/nextjs/src/@types/i18next.d.ts
  apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
  apps/nextjs/src/components/Cards/index.tsx
  apps/nextjs/src/components/Counter/Counter.tsx
  apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
  apps/nextjs/src/components/Icon/Icon.tsx
  apps/nextjs/src/components/Logo/Logo.tsx
  apps/nextjs/src/components/TextGradient/TextGradient.tsx
  apps/nextjs/src/components/Typewriter/Typewriter.tsx
  apps/nextjs/src/components/index.ts
  apps/nextjs/src/pages/_app.tsx
  apps/nextjs/src/pages/auth/error.tsx
  apps/nextjs/src/pages/auth/signin.tsx
  apps/nextjs/src/pages/index.tsx
  apps/nextjs/src/styles/globals.css
  apps/nextjs/tailwind.config.ts
  package.json
  packages/api/package.json
  packages/api/src/@types/i18next.d.ts
  packages/api/src/controllers/account.controller.ts
  packages/api/src/controllers/user.controller.ts
  packages/config/i18n/package.json
  packages/config/i18n/src/i18n.ts
  packages/config/i18n/src/i18nNamespaces.ts
  packages/config/i18n/src/index.ts
  packages/config/i18n/src/locale/en/api.json
  packages/config/i18n/src/locale/en/common.json
  packages/config/i18n/src/locale/en/nextjs.json
  packages/config/i18n/src/locale/es/api.json
  packages/config/i18n/src/locale/es/common.json
  packages/config/i18n/src/locale/es/nextjs.json
  packages/config/tailwind/index.ts
  pnpm-lock.yaml
Labels: Release

#17 [TW-15] responsive design fix
  apps/nextjs/src/components/Cards/TweetCard/TweetCard.tsx
  apps/nextjs/src/pages/index.tsx
Labels: Type: Bug
